[package]
name = "s3"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
chrono = "0.4.42"
hex = "0.4.3"
hmac = "0.12.1"
reqwest = "0.12.28"
sha2 = "0.10.9"
url = "2.5.7"
urlencoding = "2.1.3"

[lib]
